name: Deploy to Azure Function App

on:
  push:
    branches:
      - main
    paths:
      - 'functions/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd functions
        npm install

    - name: Run build
      run: |
        cd functions
        npm run build # If you have a build step

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: hnrk-test-function-app
        slot-name: production
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: functions
